"""Initial

Revision ID: cf948fe7924d
Revises: 
Create Date: 2023-12-23 07:07:07.256288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf948fe7924d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), server_default='1', autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('track',
    sa.Column('id', sa.Integer(), server_default='1', autoincrement=True, nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_carts', sa.Integer(), nullable=False),
    sa.CheckConstraint('length >= 350', name='control_length'),
    sa.CheckConstraint('max_carts >= 4', name='control_max_carts'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), server_default='1', autoincrement=True, nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('isready', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('number >= 0', name='control_number'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), server_default='1', autoincrement=True, nullable=False),
    sa.Column('count_drivers', sa.Integer(), nullable=True),
    sa.Column('timestart', sa.TIMESTAMP(), nullable=True),
    sa.Column('full_load', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('count_drivers >= 1', name='control_drivers'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), server_default='1', autoincrement=True, nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('timestart', sa.DateTime(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('count_drivers', sa.Integer(), server_default='1', nullable=False),
    sa.Column('count_slots', sa.Integer(), server_default='1', nullable=False),
    sa.Column('approved', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.CheckConstraint('count_drivers > 0', name='control_count_drivers'),
    sa.CheckConstraint('count_slots > 0', name='control_count_slots'),
    sa.CheckConstraint('price > 0', name='control_price'),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id'], onupdate='Cascade', ondelete='Cascade'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('races')
    op.drop_table('cart')
    op.drop_table('track')
    op.drop_table('clients')
    # ### end Alembic commands ###
